name: Test

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - run: docker compose up -d --wait db
      - uses: ruby/setup-ruby@d5126b9b3579e429dd52e51e68624dda2e05be25 # v1.267.0
        with:
          bundler-cache: true
      - run: bundle exec rails db:create db:migrate RAILS_ENV=test
      - run: bundle exec rspec -f j -o tmp/rspec_results.json -f d spec
      - uses: SonicGarden/rspec-report-action@59517533fc21753efb185011e1811e94dc89e02b # v6.0.0
        if: always()
        with:
          json-path: tmp/rspec_results.json
