name: Test

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: docker compose up -d --wait db
      - uses: sorah-rbpkg/actions@v2
        with:
          ruby-version-file: .ruby-version
          bundler-cache: true
      - run: bundle exec rspec -f j -o tmp/rspec_results.json -f d spec
      - uses: SonicGarden/rspec-report-action@v6
        if: always()
        with:
          json-path: tmp/rspec_results.json
